/*==============================================================*/
/* Table: APPLICATIONS                                     */
/*==============================================================*/
CREATE TABLE APPLICATIONS
(
  ID            NUMBER(22)    NOT NULL,
  CLIENT_ID     VARCHAR2(128) NOT NULL,
  CLIENT_SECRET VARCHAR2(128) NOT NULL,
  LABEL         VARCHAR2(128) NOT NULL,
  NAME          VARCHAR2(128) NOT NULL,
  CLIENT_URI    VARCHAR2(512),
  REDIRECT_URI  VARCHAR2(512),
  LOGOUT_URI    VARCHAR2(512),
  LOGO_URI      VARCHAR2(512),
  CLIENT_DESC   VARCHAR2(1024),
  ENABLED       NUMBER(2)     NOT NULL,
  CONSTRAINT PK_APPLICATIONS PRIMARY KEY (ID)
);

COMMENT ON TABLE APPLICATIONS IS
'接入应用信息';

COMMENT ON COLUMN APPLICATIONS.ID IS
'标识';

COMMENT ON COLUMN APPLICATIONS.CLIENT_ID IS
'唯一标识码';

COMMENT ON COLUMN APPLICATIONS.CLIENT_SECRET IS
'接入应用密码';

COMMENT ON COLUMN APPLICATIONS.LABEL IS
'接入应用名称';

COMMENT ON COLUMN APPLICATIONS.NAME IS
'接入应用编码';

COMMENT ON COLUMN APPLICATIONS.CLIENT_URI IS
'接入应用首页地址';

COMMENT ON COLUMN APPLICATIONS.REDIRECT_URI IS
'接入应用验证回调地址';

COMMENT ON COLUMN APPLICATIONS.LOGOUT_URI IS
'接入应用登出地址，用于单点登出';

COMMENT ON COLUMN APPLICATIONS.LOGO_URI IS
'接入应用图标地址';

COMMENT ON COLUMN APPLICATIONS.CLIENT_DESC IS
'接入应用描述';

COMMENT ON COLUMN APPLICATIONS.ENABLED IS
'可用状态(1:正常 0:冻结)';

/*==============================================================*/
/* Table: INSTITUTIONS                                     */
/*==============================================================*/
CREATE TABLE INSTITUTIONS
(
  ID                    NUMBER(22)    NOT NULL,
  LABEL                 VARCHAR2(128) NOT NULL,
  NAME                  VARCHAR2(128) NOT NULL,
  TREE_LEVEL            NUMBER(4),
  PARENT_ID             NUMBER(22),
  PATH                  VARCHAR2(4000),
  TYPE                  NUMBER(1),
  MANUAL_SN             NUMBER(4),
  ADMIN_DIVISION_CODE   VARCHAR2(20),
  ADMIN_DIVISION        VARCHAR2(128),
  ENABLED               NUMBER(2)     NOT NULL,
  SOCIAL_CREDIT_UNICODE VARCHAR2(18),
  ORG_CODE              VARCHAR2(64),
  TIME_CREATED          TIMESTAMP,
  CREATOR_ID            NUMBER(22),
  LAST_MODIFIED         TIMESTAMP,
  MODIFIER_ID           NUMBER(22),
  CREATOR               VARCHAR2(64),
  MODIFIER              VARCHAR2(64),
  CONSTRAINT PK_INSTITUTIONS PRIMARY KEY (ID)
);

COMMENT ON TABLE INSTITUTIONS IS
'组织机构信息表';

COMMENT ON COLUMN INSTITUTIONS.ID IS
'机构ID';

COMMENT ON COLUMN INSTITUTIONS.LABEL IS
'组织机构名称';

COMMENT ON COLUMN INSTITUTIONS.NAME IS
'组织机构编码';

COMMENT ON COLUMN INSTITUTIONS.TREE_LEVEL IS
'树形等级';

COMMENT ON COLUMN INSTITUTIONS.PARENT_ID IS
'父机构ID';

COMMENT ON COLUMN INSTITUTIONS.PATH IS
'树形路径';

COMMENT ON COLUMN INSTITUTIONS.TYPE IS
'类型 1:机构 2:部门';

COMMENT ON COLUMN INSTITUTIONS.MANUAL_SN IS
'手动排序';

COMMENT ON COLUMN INSTITUTIONS.ADMIN_DIVISION_CODE IS
'行政区划代码';

COMMENT ON COLUMN INSTITUTIONS.ADMIN_DIVISION IS
'行政区划';

COMMENT ON COLUMN INSTITUTIONS.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN INSTITUTIONS.SOCIAL_CREDIT_UNICODE IS
'社会信用统一代码';

COMMENT ON COLUMN INSTITUTIONS.ORG_CODE IS
'组织机构代码';

COMMENT ON COLUMN INSTITUTIONS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN INSTITUTIONS.CREATOR_ID IS
'创建人ID';

COMMENT ON COLUMN INSTITUTIONS.LAST_MODIFIED IS
'更新时间';

COMMENT ON COLUMN INSTITUTIONS.MODIFIER_ID IS
'更新人ID';

COMMENT ON COLUMN INSTITUTIONS.CREATOR IS
'创建人';

COMMENT ON COLUMN INSTITUTIONS.MODIFIER IS
'更新人';

/*==============================================================*/
/* Table: OPERATIONS                                       */
/*==============================================================*/
CREATE TABLE OPERATIONS
(
  ID             NUMBER(22)    NOT NULL,
  LABEL          VARCHAR2(128) NOT NULL,
  NAME           VARCHAR2(128) NOT NULL,
  MANUAL_SN      NUMBER(4),
  PARENT_ID      NUMBER(22),
  TREE_LEVEL     NUMBER(4),
  PATH           VARCHAR2(4000),
  RES_URL        VARCHAR2(256),
  ICON_PATH      VARCHAR2(128),
  OPT_TYPE       NUMBER(2)     NOT NULL,
  ENABLED        NUMBER(2),
  APPLICATION_ID NUMBER(22),
  CONSTRAINT PK_OPERATIONS PRIMARY KEY (ID)
);

COMMENT ON TABLE OPERATIONS IS
'系统操作项表';

COMMENT ON COLUMN OPERATIONS.ID IS
'操作ID';

COMMENT ON COLUMN OPERATIONS.LABEL IS
'操作名称';

COMMENT ON COLUMN OPERATIONS.NAME IS
'操作编码';

COMMENT ON COLUMN OPERATIONS.MANUAL_SN IS
'手动排序';

COMMENT ON COLUMN OPERATIONS.PARENT_ID IS
'父亲ID';

COMMENT ON COLUMN OPERATIONS.TREE_LEVEL IS
'树形层级';

COMMENT ON COLUMN OPERATIONS.PATH IS
'树形路径';

COMMENT ON COLUMN OPERATIONS.RES_URL IS
'操作URL';

COMMENT ON COLUMN OPERATIONS.ICON_PATH IS
'操作图标路径';

COMMENT ON COLUMN OPERATIONS.OPT_TYPE IS
'操作类型(1:菜单 2:按钮)';

COMMENT ON COLUMN OPERATIONS.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN OPERATIONS.APPLICATION_ID IS
'应用ID';

/*==============================================================*/
/* Table: PRIVILEGES                                       */
/*==============================================================*/
CREATE TABLE PRIVILEGES
(
  ID      NUMBER(22)    NOT NULL,
  LABEL   VARCHAR2(128) NOT NULL,
  NAME    VARCHAR2(128) NOT NULL,
  ENABLED NUMBER(2)     NOT NULL,
  REMARKS VARCHAR2(512),
  CONSTRAINT PK_PRIVILEGES PRIMARY KEY (ID)
);

COMMENT ON TABLE PRIVILEGES IS
'权限信息表';

COMMENT ON COLUMN PRIVILEGES.ID IS
'权限ID';

COMMENT ON COLUMN PRIVILEGES.LABEL IS
'权限名称';

COMMENT ON COLUMN PRIVILEGES.NAME IS
'权限编码';

COMMENT ON COLUMN PRIVILEGES.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN PRIVILEGES.REMARKS IS
'备注';

/*==============================================================*/
/* Table: PRIVILEGE_OPERATION                              */
/*==============================================================*/
CREATE TABLE PRIVILEGE_OPERATION
(
  PRIV_ID NUMBER(22) NOT NULL,
  OPER_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE PRIVILEGE_OPERATION IS
'权限操作关系表';

COMMENT ON COLUMN PRIVILEGE_OPERATION.PRIV_ID IS
'权限ID';

COMMENT ON COLUMN PRIVILEGE_OPERATION.OPER_ID IS
'功能ID';

/*==============================================================*/
/* Table: PRIVILEGE_ROLE                                   */
/*==============================================================*/
CREATE TABLE PRIVILEGE_ROLE
(
  PRIV_ID NUMBER(22) NOT NULL,
  ROLE_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE PRIVILEGE_ROLE IS
'权限角色关系表';

COMMENT ON COLUMN PRIVILEGE_ROLE.PRIV_ID IS
'权限ID';

COMMENT ON COLUMN PRIVILEGE_ROLE.ROLE_ID IS
'角色ID';

/*==============================================================*/
/* Table: ROLES                                            */
/*==============================================================*/
CREATE TABLE ROLES
(
  ID      NUMBER(22)    NOT NULL,
  LABEL   VARCHAR2(128) NOT NULL,
  NAME    VARCHAR2(128) NOT NULL,
  ENABLED NUMBER(2)     NOT NULL,
  REMARKS VARCHAR2(512),
  CONSTRAINT PK_ROLES PRIMARY KEY (ID)
);

COMMENT ON TABLE ROLES IS
'系统角色表';

COMMENT ON COLUMN ROLES.ID IS
'角色ID';

COMMENT ON COLUMN ROLES.LABEL IS
'角色名称';

COMMENT ON COLUMN ROLES.NAME IS
'角色编码';

COMMENT ON COLUMN ROLES.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN ROLES.REMARKS IS
'备注';

/*==============================================================*/
/* Table: STAFFS                                           */
/*==============================================================*/
CREATE TABLE STAFFS
(
  ID                  NUMBER(22) NOT NULL,
  NAME                VARCHAR2(64),
  TEL                 VARCHAR2(32),
  MOBILE              VARCHAR2(32),
  ZIP_CODE            VARCHAR2(32),
  EMAIL               VARCHAR2(64),
  EXTRANET_EMAIL      VARCHAR2(64),
  ALIAS_NAMES         VARCHAR2(64),
  SEX                 NUMBER(2),
  PICTURE_URL         VARCHAR2(256),
  PROFESSIONAL_TITLE  VARCHAR2(64),
  OFFICAL_POST        VARCHAR2(64),
  OFFICAL_DUTY        VARCHAR2(64),
  EMPLOYEE_TYPE       VARCHAR2(64),
  EMPLOYEE_NO         VARCHAR2(64),
  CITIZEN_ID_NUMBER   VARCHAR2(18),
  BIRTHDAY            DATE,
  ADMIN_DIVISION_CODE VARCHAR2(18),
  ADMIN_DIVISION      VARCHAR2(128),
  CUR_RESIDENCE       VARCHAR2(512),
  REMARKS             VARCHAR2(512),
  LAST_MODIFIED       TIMESTAMP,
  MODIFIER_ID         NUMBER(22),
  MODIFIER            VARCHAR2(64),
  TIME_CREATED        TIMESTAMP,
  CREATOR_ID          NUMBER(22),
  CREATOR             VARCHAR2(64),
  CONSTRAINT PK_STAFFS PRIMARY KEY (ID)
);

COMMENT ON TABLE STAFFS IS
'员工信息表';

COMMENT ON COLUMN STAFFS.ID IS
'员工ID';

COMMENT ON COLUMN STAFFS.NAME IS
'员工姓名';

COMMENT ON COLUMN STAFFS.TEL IS
'固定电话号';

COMMENT ON COLUMN STAFFS.MOBILE IS
'手机号码';

COMMENT ON COLUMN STAFFS.ZIP_CODE IS
'邮编';

COMMENT ON COLUMN STAFFS.EMAIL IS
'内网邮箱';

COMMENT ON COLUMN STAFFS.EXTRANET_EMAIL IS
'外网邮箱';

COMMENT ON COLUMN STAFFS.ALIAS_NAMES IS
'别名,多个用逗号隔开';

COMMENT ON COLUMN STAFFS.PICTURE_URL IS
'照片URL';

COMMENT ON COLUMN STAFFS.SEX IS
'性别(1:男 2:女)';

COMMENT ON COLUMN STAFFS.PROFESSIONAL_TITLE IS
'职称';

COMMENT ON COLUMN STAFFS.OFFICAL_POST IS
'职务';

COMMENT ON COLUMN STAFFS.OFFICAL_DUTY IS
'职责';

COMMENT ON COLUMN STAFFS.EMPLOYEE_TYPE IS
'员工类别';

COMMENT ON COLUMN STAFFS.EMPLOYEE_NO IS
'员工工号';

COMMENT ON COLUMN STAFFS.CITIZEN_ID_NUMBER IS
'身份证号码';

COMMENT ON COLUMN STAFFS.BIRTHDAY IS
'出生日期';

COMMENT ON COLUMN STAFFS.ADMIN_DIVISION_CODE IS
'居住地行政区划编号';

COMMENT ON COLUMN STAFFS.ADMIN_DIVISION IS
'居住地行政区划';

COMMENT ON COLUMN STAFFS.CUR_RESIDENCE IS
'现居住地址';

COMMENT ON COLUMN STAFFS.REMARKS IS
'备注说明';

COMMENT ON COLUMN STAFFS.LAST_MODIFIED IS
'更新时间';

COMMENT ON COLUMN STAFFS.MODIFIER_ID IS
'更新人ID';

COMMENT ON COLUMN STAFFS.MODIFIER IS
'更新人';

COMMENT ON COLUMN STAFFS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN STAFFS.CREATOR_ID IS
'创建人ID';

COMMENT ON COLUMN STAFFS.CREATOR IS
'创建人';

/*==============================================================*/
/* Table: STAFF_INSTITUTION                                */
/*==============================================================*/
CREATE TABLE USER_INSTITUTION
(
  USER_ID  NUMBER(22) NOT NULL,
  INSTITUTION_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE USER_INSTITUTION IS
'用户组织机构关系表';

COMMENT ON COLUMN USER_INSTITUTION.INSTITUTION_ID IS
'组织机构ID';

COMMENT ON COLUMN USER_INSTITUTION.USER_ID IS
'用户ID';

/*==============================================================*/
/* Table: USERS                                            */
/*==============================================================*/
CREATE TABLE USERS
(
  ID            NUMBER(22)   NOT NULL,
  LOGIN_NAME    VARCHAR2(64) NOT NULL,
  PASSWORD      VARCHAR2(64) NOT NULL,
  SALT          VARCHAR2(64),
  NAME          VARCHAR2(64),
  USER_NO       VARCHAR2(64),
  ENABLED       NUMBER(2)    NOT NULL,
  STAFF_ID      NUMBER(22),
  REMARKS       VARCHAR2(512),
  PWD_MODIFIED  TIMESTAMP,
  LAST_MODIFIED TIMESTAMP,
  MODIFIER_ID   NUMBER(22),
  MODIFIER      VARCHAR2(64),
  TIME_CREATED  TIMESTAMP    NOT NULL,
  CREATOR_ID    NUMBER(22),
  CREATOR       VARCHAR2(64),
  CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

COMMENT ON TABLE USERS IS
'系统用户表';

COMMENT ON COLUMN USERS.ID IS
'用户ID';

COMMENT ON COLUMN USERS.LOGIN_NAME IS
'登录名';

COMMENT ON COLUMN USERS.PASSWORD IS
'密码';

COMMENT ON COLUMN USERS.USER_NO IS
'用户编号';

COMMENT ON COLUMN USERS.SALT IS
'加密盐值';

COMMENT ON COLUMN USERS.NAME IS
'姓名';

COMMENT ON COLUMN USERS.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN USERS.STAFF_ID IS
'关联员工ID';

COMMENT ON COLUMN USERS.REMARKS IS
'备注说明';

COMMENT ON COLUMN USERS.PWD_MODIFIED IS
'最后修改密码日期';

COMMENT ON COLUMN USERS.LAST_MODIFIED IS
'更新时间';

COMMENT ON COLUMN USERS.MODIFIER_ID IS
'更新人ID';

COMMENT ON COLUMN USERS.MODIFIER IS
'更新人';

COMMENT ON COLUMN USERS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN USERS.CREATOR_ID IS
'创建人ID';

COMMENT ON COLUMN USERS.CREATOR IS
'创建人';

/*==============================================================*/
/* Table: USER_ROLE                                        */
/*==============================================================*/
CREATE TABLE USER_ROLE
(
  ROLE_ID NUMBER(22) NOT NULL,
  USER_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE USER_ROLE IS
'用户角色关系表';

COMMENT ON COLUMN USER_ROLE.ROLE_ID IS
'角色ID';

COMMENT ON COLUMN USER_ROLE.USER_ID IS
'用户ID';

-- Create/Recreate foreign key constraints

ALTER TABLE OPERATIONS
  ADD CONSTRAINT FK_OPERATIONS_APP_ID FOREIGN KEY (APPLICATION_ID)
REFERENCES APPLICATIONS (ID) ON DELETE CASCADE;

ALTER TABLE PRIVILEGE_OPERATION
  ADD CONSTRAINT FK_PRIV_OPER_OPER_ID FOREIGN KEY (OPER_ID)
REFERENCES OPERATIONS (ID) ON DELETE CASCADE;

ALTER TABLE PRIVILEGE_OPERATION
  ADD CONSTRAINT FK_PRIV_OPER_PRIV_ID FOREIGN KEY (PRIV_ID)
REFERENCES PRIVILEGES (ID) ON DELETE CASCADE;

ALTER TABLE PRIVILEGE_ROLE
  ADD CONSTRAINT FK_PRIV_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID)
REFERENCES ROLES (ID) ON DELETE CASCADE;

ALTER TABLE PRIVILEGE_ROLE
  ADD CONSTRAINT FK_PRIV_ROLE_PRIV_ID FOREIGN KEY (PRIV_ID)
REFERENCES PRIVILEGES (ID) ON DELETE CASCADE;

ALTER TABLE USERS
  ADD CONSTRAINT FK_USERS_STAFFS_ID FOREIGN KEY (STAFF_ID)
REFERENCES STAFFS (ID) ON DELETE CASCADE;

ALTER TABLE USER_INSTITUTION
  ADD CONSTRAINT FK_USER_INST_USER_ID FOREIGN KEY (USER_ID)
REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE USER_INSTITUTION
  ADD CONSTRAINT FK_USER_INST_INST_ID FOREIGN KEY (INSTITUTION_ID)
REFERENCES INSTITUTIONS (ID) ON DELETE CASCADE;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY (USER_ID)
REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT FK_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID)
REFERENCES ROLES (ID) ON DELETE CASCADE;

-- Create/Recreate unique key constraints
ALTER TABLE USERS
  ADD CONSTRAINT UN_USERS_LOGIN_NAME UNIQUE (LOGIN_NAME);

ALTER TABLE ROLES
  ADD CONSTRAINT UN_ROLES_NAME UNIQUE (NAME);

ALTER TABLE APPLICATIONS
  ADD CONSTRAINT APPLICATIONS_NAME UNIQUE (NAME);

ALTER TABLE OPERATIONS
  ADD CONSTRAINT OPERATIONS_NAME UNIQUE (NAME);

ALTER TABLE INSTITUTIONS
  ADD CONSTRAINT INSTITUTIONS_NAME UNIQUE (NAME);

ALTER TABLE PRIVILEGES
  ADD CONSTRAINT PRIVILEGES UNIQUE (NAME);
