CREATE SEQUENCE INSTITUTIONS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE APPLICATIONS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE OPERATIONS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PRIVILEGES_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USERS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ROLES_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE STAFFS_S START WITH 1 INCREMENT BY 1;
